ProductionMonitoring/Models/ErrorViewModel.cs
namespace ProductionMonitoring.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProductionMonitoring/Controllers/DailyReportController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductionMonitoring.Controllers
{
    public class DailyReportController : Controller
    {
        public IActionResult DailyReport()
        {
            return View();
        }

        public IActionResult AddNote() 
        {
            return View();
        }

        public IActionResult DailyMonth() 
        {
            return View();
        }

        public IActionResult AddMonth() 
        {
            return View();
        }

        public IActionResult MonthResult()
        {
            ViewData["Pagename"] = "MonthResult";
            return View();
        }
    }
}

ProductionMonitoring/Controllers/DataUserController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductionMonitoring.Controllers
{
    public class DataUserController : Controller
    {
        public IActionResult DataUser()
        {
            return View();
        }

        public IActionResult AddUser() 
        {
            return View();
        }
    }
}

ProductionMonitoring/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProductionMonitoring.Models;
using System.Diagnostics;

namespace ProductionMonitoring.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Display()
        {
            ViewData["Pagename"] = "Display";
            return View();
        }
    }
}

ProductionMonitoring/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductionMonitoring.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LoginProcess() 
        {
            return RedirectToAction("Index", "Home");
        }
    }
}

ProductionMonitoring/Controllers/ModelNumberController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductionMonitoring.Controllers
{
    public class ModelNumberController : Controller
    {
        public IActionResult ModelNumber()
        {
            return View();
        }

        public IActionResult Add() 
        {
            return View();
        }
    }
}

ProductionMonitoring/Controllers/MonitoringController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductionMonitoring.Controllers
{
    public class MonitoringController : Controller
    {
        public IActionResult Monitoring()
        {
            return View();
        }

        public IActionResult Show() 
        {
            ViewData["Pagename"] = "Show";
            return View();
        }
    }
}

ProductionMonitoring/Controllers/PlanController.cs
using Microsoft.AspNetCore.Mvc;
using ProductionMonitoring.Models;

namespace ProductionMonitoring.Controllers
{
    public class PlanController : Controller
    {
       /* private readonly ApplicationDbContext dbContext;

        public PlanController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }*/
        public IActionResult Plan()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
/*
        [HttpPost]
        public async Task<IActionResult> Add(AddPlanViewModel viewModel)
        {
            var plan = new Plan
            {
                Date = DateTime.Now,
                ModelCode = viewModel.ModelCode,
                ModelNumber = viewModel.ModelNumber,
                Cycletime = viewModel.Cycletime,
                Plann = viewModel.Plann,
                Actual = viewModel.Actual,
                Balancing = viewModel.Balancing,
                Status = viewModel.Status
            };

            await dbContext.Plans.AddAsync(plan);
            await dbContext.SaveChangesAsync();

            return View();
        }*/
    }
}

ProductionMonitoring/Controllers/ProductionController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductionMonitoring.Controllers
{
    public class ProductionController : Controller
    {
        public IActionResult Month()
        {
            return View();
        }

        public IActionResult Day()
        {
            return View();
        }
    }
}

ProductionMonitoring/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductionMonitoring.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Profile()
        {
            return View();
        }
    }
}

ProductionMonitoring/Controllers/WorkTimeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProductionMonitoring.Controllers
{
    public class WorkTimeController : Controller
    {
        public IActionResult WorkTime()
        {
            return View();
        }
    }
}

ProductionMonitoring/Views/DataUser/AddUser.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row">
    <div class="col-xl">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="mb-0">Add New User</h5>
            </div>
            <div class="card-body">
                <form method="post">
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Full Name</label>
                        <input type="text" class="form-control" id="basic-default-company" placeholder="Full Name" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Username</label>
                        <input type="text" class="form-control" id="basic-default-company" placeholder="Username" />
                        @* <div class="form-text">You can use letters, numbers & periods</div> *@
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Email</label>
                        <input type="email" class="form-control" id="basic-default-company" placeholder="example" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Password</label>
                        <input type="password" class="form-control" id="basic-default-company" value="12345678" />
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlSelect1" class="form-label">Level</label>
                        <select class="form-select" id="exampleFormControlSelect1" aria-label="Default select example" />
                        <option selected>Level</option>
                        <option value="1">Admin</option>
                        <option value="2">Spv</option>
                        </select>
                    </div>
                    <a type="submit" class="btn btn-primary" asp-controller="DataUser" asp-action="DataUser">Send</a>
                </form>
            </div>
        </div>
    </div>
</div>

ProductionMonitoring/Views/DataUser/DataUser.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Pagename"] = "Data";
}

<div class="card">
    <div class="d-flex align-items-center justify-content-between">
        <h3 class="card-header">Data User</h3>
        <a class="btn btn-primary btn-sm me-4" asp-controller="Datauser" asp-action="AddUser" type="submit"><i class='bx bx-plus-circle'></i><span>Add New User</span></a>
    </div>
    <div class="card-body">
        <div class="table-responsive text-nowrap">
            <table class="table table-bordered text-center">
                <thead>
                    <tr>
                        <th class="fs-6 fw-bolder">No</th>
                        <th class="fs-6 fw-bolder">Full Name</th>
                        <th class="fs-6 fw-bolder">Username</th>
                        <th class="fs-6 fw-bolder">Password</t>
                        <th class="fs-6 fw-bolder">Level</th>
                        <th class="fs-6 fw-bolder">Status</th>
                        <th class="fs-6 fw-bolder">Action</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    <tr>
                        <td>1</td>
                        <td>Bryan Doe</td>
                        <td>bryan</td>
                        <td>********</td>
                        <td>admin</td>
                        <td><span class="badge bg-label-primary me-1">Active</span></td>
                        <td class="d-flex justify-content-center">
                            <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-edit-alt"></i></a>
                            <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-trash text-danger"></i></a>
                        </td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>Bryan Doe</td>
                        <td>bryan</td>
                        <td>********</td>
                        <td>admin</td>
                        <td><span class="badge bg-label-primary me-1">Active</span></td>
                        <td class="d-flex justify-content-center">
                            <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-edit-alt"></i></a>
                            <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-trash text-danger"></i></a>
                        </td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>Bryan Doe</td>
                        <td>bryan</td>
                        <td>********</td>
                        <td>Spv</td>
                        <td><span class="badge bg-label-primary me-1">Active</span></td>
                        <td class="d-flex justify-content-center">
                            <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-edit-alt"></i></a>
                            <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-trash text-danger"></i></a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

ProductionMonitoring/Views/ModelNumber/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row">
    <div class="col-xl">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="mb-0">Add Model Product</h5>
            </div>
            <div class="card-body">
                <form method="post">
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Model Number</label>
                        <input type="text" class="form-control" id="basic-default-company" placeholder="Model Number" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Model Code</label>
                        <input type="text" class="form-control" id="basic-default-company" placeholder="Model Code"  />
                        @* <div class="form-text">You can use letters, numbers & periods</div> *@
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Cycle Time</label>
                        <input type="number" class="form-control" id="basic-default-company" placeholder="00.00"  />
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlSelect1" class="form-label">Status</label>
                        <select class="form-select" id="exampleFormControlSelect1" aria-label="Default select example" />
                            <option selected>Status</option>
                            <option value="1">Active</option>
                            <option value="2">Inactive</option>
                        </select>
                    </div>
                    <a type="submit" class="btn btn-primary" asp-controller="ModelNumber" asp-action="ModelNumber">Send</a>
                </form>
            </div>
        </div>
    </div>
</div>

ProductionMonitoring/Views/ModelNumber/ModelNumber.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Pagename"] = "Model";
}

<div class="card">
        <div class="d-flex align-items-center justify-content-between mx-3">
            <h3 class="card-header">Model Number</h3>
            <div class="nav-item d-flex align-items-center">
                <i class="bx bx-search fs-4 lh-0"></i>
                <input type="text"
                       class="form-control border-1 shadow-none bg-white"
                       placeholder="Search..."
                       aria-label="Search..." />
            </div>
                 <a class="btn btn-primary btn-sm" asp-controller="ModelNumber" asp-action="Add" type="submit"><i class='bx bx-plus-circle'></i><span class="ms-2">Add new Model</span></a>
        </div>
    <div class="table-responsive text-nowrap">
        <table class="table table-striped">
            <thead class="text-center">
                <tr>
                    <th class="fs-6 fw-bolder">Model Number</th>
                    <th class="fs-6 fw-bolder">Model Code</th>
                    <th class="fs-6 fw-bolder">Cycle Time</th>
                    <th class="fs-6 fw-bolder">Status</th>
                    <th class="fs-6 fw-bolder">Actions</th>
                </tr>
            </thead>
            <tbody class="table-border-bottom-0 text-center">
                <tr>
                    <td>NA-W86BBZ2D</td>
                    <td>3N</td>
                    <td>34.0</td>
                    <td><span class="badge bg-label-success me-1">Active</span></td>
                    <td class="d-flex align-items-center  justify-content-center">
                        <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-edit-alt"></i></a>
                        <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-trash text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>NA-W86BBZ2H</td>
                    <td>3N</td>
                    <td>34.0</td>
                    <td><span class="badge bg-label-secondary me-1">Inactive</span></td>
                    <td class="d-flex justify-content-center ">
                        <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-edit-alt"></i></a>
                        <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-trash text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>NA-W86FCU1G</td>
                    <td>3N</td>
                    <td>33.0</td>
                    <td><span class="badge bg-label-success me-1">Active</span></td>
                    <td class="d-flex justify-content-center ">
                        <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-edit-alt"></i></a>
                        <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-trash text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>NA-W96BBZ2H</td>
                    <td>3N</td>
                    <td>34.0</td>
                    <td><span class="badge bg-label-success me-1">Active</span></td>
                    <td class="d-flex justify-content-center ">
                        <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-edit-alt"></i></a>
                        <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-trash text-danger"></i></a>
                    </td>
                </tr>
                <tr>
                    <td>NA-W96FCU1G</td>
                    <td>3N</td>
                    <td>34.0</td>
                    <td><span class="badge bg-label-success me-1">Active</span></td>
                    <td class="d-flex justify-content-center">
                        <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-edit-alt"></i></a>
                        <a class="dropdown-item" href="javascript:void(0);"><i class="bx bx-trash text-danger"></i></a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

ProductionMonitoring/Views/Plan/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="row">
    <div class="col-xl">
        <div class="card mb-4">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5 class="mb-0">Add Planning</h5>
            </div>
            <div class="card-body">
                <form method="post">
                    <div class="mb-3">
                        <label for="html5-date-input" class="col-md-2 col-form-label">Date</label>
                        <input class="form-control" type="date" value="dd/mm/yyyy" id="html5-date-input"/>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Model Code</label>
                        <input type="text" class="form-control" id="basic-default-company" placeholder="Model Code"/>
                        @* <div class="form-text">You can use letters, numbers & periods</div> *@
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Model Number</label>
                        <input type="text" class="form-control" id="basic-default-company" placeholder="Model Number"/>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Cycle Time</label>
                        <input type="number" class="form-control" id="basic-default-company" placeholder="00.00"/>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Plan</label>
                        <input type="number" class="form-control" id="basic-default-company" placeholder="000"/>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Actual</label>
                        <input type="number" class="form-control" id="basic-default-company" placeholder="000" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label" for="basic-default-company">Balancing</label>
                        <input type="number" class="form-control" id="basic-default-company" placeholder="000"/>
                    </div>
                    <div class="mb-3">
                        <label for="exampleFormControlSelect1" class="form-label">Status</label>
                        <select class="form-select" id="exampleFormControlSelect1" aria-label="Default select example">
                            <option selected>Status</option>
                            <option value="1">Active</option>
                            <option value="2">Inactive</option>
                        </select>
                    </div>
                    <a type="submit" class="btn btn-primary" asp-controller="Plan" asp-action="Plan">Send</a>
                </form>
            </div>
        </div>
    </div>
</div>

ProductionMonitoring/Views/Shared/_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<footer class="content-footer footer bg-footer-theme">
    <div class="container-fluid container-fluid-xxl d-flex flex-wrap justify-content-between flex-md-row flex-column">
        <div class="fixed">
            ©
            <script>
                document.write(new Date().getFullYear());
            </script>
            , Create by
            <h6 class="footer-link fw-bolder">POLITEKNIK ELEKTRONIKA NEGERI SURABAYA</h6>
        </div>
    </div>
</footer>

ProductionMonitoring/Views/Shared/_Navbar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<nav class="layout-navbar container-fluid-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme @(ViewData["Pagename"] == "Home Page" || ViewData["Pagename"] == "Time" || ViewData["Pagename"] == "Monitoring" || ViewData["Pagename"] == "Login" ? "d-none" : "")"
     id="layout-navbar">
    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
        <a class="nav-item nav-link px-0 me-xl-4 d-flex">
                <i class="bx bx-menu bx-sm"></i>
            <img src="~/assets/img/panasonic.png" class="app-brand-text demo menu-text ms-2" style="width: 70px" />
        </a>
    </div>

    <div class="navbar-nav-right d-flex align-items-center justify-content-center" id="navbar-collapse">
        <!-- Search -->
        <div class="navbar-nav align-items-center d-md-none d-sm-none d-xl-block">
            <div class="nav-item d-flex align-items-center">
                <i class="bx bx-search fs-4 lh-0"></i>
                <input type="text"
                       class="form-control border-0 shadow-none"
                       placeholder="Search..."
                       aria-label="Search..." />
            </div>
        </div>
        <!-- /Search -->

        @* <ul class="navbar-nav flex-row align-items-center ms-auto">

            <!-- User -->
            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                <a class="nav-link dropdown-toggle hide-arrow " href="javascript:void(0);" data-bs-toggle="dropdown">
                    <div class="avatar avatar-online justify-content-center align-items-center">
                        <img src="~/lib/theme/img/avatars/1.png" class="w-px-40 h-auto rounded-circle" />
                    </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <a class="dropdown-item" href="#">
                            <div class="d-flex">
                                <div class="flex-shrink-0 me-3">
                                    <div class="avatar avatar-online">
                                        <img src="~/lib/theme/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle" />
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    <span class="fw-semibold d-block">John Doe</span>
                                    <small class="text-muted">Admin</small>
                                </div>
                            </div>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <a class="dropdown-item" asp-controller="User" asp-action="Profile">
                            <i class="bx bx-user me-2"></i>
                            <span class="align-middle">My Profile</span>
                        </a>
                    </li>
                    <li>
                        <div class="dropdown-divider"></div>
                    </li>
                    <li>
                        <a class="dropdown-item" href="auth-login-basic.html">
                            <i class="bx bx-power-off me-2"></i>
                            <span class="align-middle">Log Out</span>
                        </a>
                    </li>
                </ul>
            </li>
            <!--/ User -->
        </ul> *@
    </div>
</nav>

ProductionMonitoring/Views/Shared/_SideBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
   
}
<div class="container pe-0 @(ViewData["PageName"] == "Show" || ViewData["PageName"] == "Display"  ? "d-none" : "")">
        <aside class="sidebar active">
            <div class="menu-btn">
                <i class='bx bxs-left-arrow-circle'></i>
            </div>
            <div class="head">
                <div class="user-img">
                <a asp-controller="User" asp-action="Profile"> <img src="~/assets/img/1.png" class="w-px-40 h-auto rounded-circle" /></a>
                </div>
                <div class="user-details">
                    <p class="name my-0">Akbar</p>
                    <p class="title">Admin</p>
                </div>
            </div>
            <nav class="nav">
                <div class="menu">
                    <ul>
                        <li class="active">
                            <a asp-controller="Home" asp-action="Index">
                                <i class="icon bx bx-grid-alt"></i>
                                <span class="text">Summary</span>
                            </a>
                        </li>
                        <li class="active">
                            <a >
                                <i class="icon bx bx-receipt"></i>
                                <span class="text">Daily Report</span>
                                <i class='arrow bx bx-chevron-down'></i>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a asp-controller ="DailyReport" asp-action="DailyReport">
                                        <i class="icon bx bx-receipt"></i>
                                        <span class="text">Report Daily</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="DailyReport" asp-action="DailyMonth">
                                        <i class="icon bx bx-receipt"></i>
                                        <span class="text">Report Month</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="DailyReport" asp-action="MonthResult">
                                        <i class="icon bx bx-receipt"></i>
                                        <span class="text">Monthly Result</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="active">
                            <a asp-controller="Plan" asp-action="Plan">
                                <i class='icon bx bx-line-chart'></i>
                                <span class="text">Planning</span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <i class="icon bx bx-box"></i>
                                <span class="text">Production</span>
                                <i class='arrow bx bx-chevron-down'></i>
                            </a>
                            <ul class="sub-menu">
                                <li>
                                    <a asp-controller="Production" asp-action="Day">
                                        <i class="icon bx bxs-calendar"></i>
                                        <span class="text">Daily</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="Production" asp-action="Month">
                                        <i class="icon bx bxs-moon"></i>
                                        <span class="text">Month</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="active">
                            <a asp-controller="ModelNumber" asp-action="ModelNumber">
                                <i class="icon bx bxs-package"></i>
                                <span class="text">Model Number</span>
                            </a>
                        </li>
                        <li class="active">
                            <a asp-action="Monitoring" asp-controller="Monitoring">
                                <i class="icon bx bx-desktop"></i>
                                <span class="text">Monitoring</span>
                            </a>
                        </li>
                        <li class="active">
                            <a asp-action="WorkTime" asp-controller="WorkTime">
                                <i class="icon bx bx-time"></i>
                                <span class="text">Work Time</span>
                            </a>
                        </li>
                        <li class="active">
                            <a asp-controller="DataUser" asp-action="DataUser">
                                <i class="icon bx bx-user"></i>
                                <span class="text">Data User</span>
                            </a>
                        </li>
                        <li class="active">
                            <a asp-controller="Login" asp-action="Login" class="text-danger">
                                <i class="icon bx bx-log-out"></i>
                                <span class="text">Logout</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </aside>
    </div>